import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

type Client={id:number;name:string;company?:string;manager?:string;phone?:string;email?:string;trade_place?:string;birth_date?:string;last_import_at?:string;status:string};
const api=(path:string, init?:RequestInit)=>fetch(`/api${path}`,init).then(r=>r.json());
function App(){
 const [clients,setClients]=useState<Client[]>([]),[total,setTotal]=useState(0),[q,setQ]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<number[]>([]),[detail,setDetail]=useState<any>(null),[imports,setImports]=useState<any[]>([]),[notice,setNotice]=useState(''),[drag,setDrag]=useState(false);
 const [filters,setFilters]=useState({manager:'',company:'',price_type:'',status:'',has_email:'',has_phone:'',sort:'name',order:'asc'});
 const query=useMemo(()=>new URLSearchParams({page:String(page),page_size:'50',search:q,...Object.fromEntries(Object.entries(filters).filter(([,v])=>v))}).toString(),[q,page,filters]);
 const load=()=>api(`/clients?${query}`).then(d=>{setClients(d.items);setTotal(d.total)});
 useEffect(()=>{load();api('/imports').then(setImports)},[query]);
 const upload=async(files:FileList|null)=>{if(!files?.length)return; const fd=new FormData(); [...files].forEach(f=>fd.append('files',f)); setNotice(`Загрузка файлов: ${files.length}`); const r=await api('/imports',{method:'POST',body:fd}); setNotice(`${r.message}. Добавлено: ${r.added}. Обновлено: ${r.updated}. Пропущено: ${r.skipped}. Ошибок: ${r.errors}`); load(); api('/imports').then(setImports)};
 const bulk=async(payload:any)=>{await api('/clients/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected,...payload})});setSelected([]);load();setNotice('Операция выполнена')};
 return <main><header><h1>База клиентов</h1><p>Поиск, импорт Excel, журнал операций и массовые действия</p></header><section className="toolbar"><input placeholder="Мгновенный поиск по клиентам, email, телефонам..." value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Все статусы</option><option value="active">Активный</option><option value="archived">Архивный</option></select><select onChange={e=>setFilters({...filters,has_email:e.target.value})}><option value="">Email: все</option><option value="true">Есть Email</option><option value="false">Нет Email</option></select><select onChange={e=>setFilters({...filters,sort:e.target.value})}><option value="name">Сортировка: наименование</option><option value="company">Фирма</option><option value="manager">Менеджер</option><option value="birth_date">Дата рождения</option><option value="updated_at">Обновление</option><option value="last_import">Импорт</option></select><a className="button" href="/api/clients-export.xlsx">⬇️ Экспорт</a></section>
 <section className={`drop ${drag?'active':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);upload(e.dataTransfer.files)}}>⬆️ <b>Импорт .xls/.xlsx</b><span>Перетащите файлы сюда или выберите несколько файлов</span><input type="file" multiple accept=".xls,.xlsx" onChange={e=>upload(e.target.files)}/></section>{notice&&<div className="notice">{notice}</div>}
 <section className="bulk"><span>Выбрано: {selected.length}</span><button disabled={!selected.length} onClick={()=>bulk({status:'archived'})}>📦 Архивировать</button><button disabled={!selected.length} onClick={()=>bulk({manager:prompt('Новый менеджер')})}>Сменить менеджера</button><button disabled={!selected.length} onClick={()=>bulk({price_type:prompt('Новый тип цены')})}>Сменить тип цены</button><button disabled={!selected.length} onClick={async()=>{await fetch(`/api/clients?ids=${selected.join(',')}`,{method:'DELETE'});setSelected([]);load()}}>🗑️ Удалить</button></section>
 <div className="grid"><section className="table"><table><thead><tr><th></th><th>Наименование</th><th>Фирма</th><th>Менеджер</th><th>Телефон</th><th>Email</th><th>Место торговли</th><th>Дата рождения</th><th>Последний импорт</th><th>Статус</th></tr></thead><tbody>{clients.map(c=><tr key={c.id} onClick={()=>api(`/clients/${c.id}`).then(setDetail)}><td onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/></td><td>{c.name}</td><td>{c.company}</td><td>{c.manager}</td><td>{c.phone}</td><td>{c.email}</td><td>{c.trade_place}</td><td>{c.birth_date}</td><td>{c.last_import_at?.slice(0,10)}</td><td><span className={c.status}>{c.status==='active'?'Активный':'Архивный'}</span></td></tr>)}</tbody></table><footer><button disabled={page===1} onClick={()=>setPage(page-1)}>Назад</button><span>{page} / {Math.ceil(total/50)||1} · {total} записей</span><button disabled={page*50>=total} onClick={()=>setPage(page+1)}>Вперед</button></footer></section>
 <aside>{detail?<ClientCard c={detail}/>:<ImportHistory imports={imports}/>}</aside></div></main>}
function ClientCard({c}:{c:any}){return <div className="card"><h2>{c.name}</h2><Block title="Основная информация" rows={[['Фирма',c.company],['Тип цены',c.price_type],['Менеджер',c.manager]]}/><Block title="Контакты" rows={[['Контактное лицо',c.contact_person],['Руководитель',c.director],['Email',c.emails?.join(', ')],['Все телефоны',c.phones?.map((p:any)=>`${p.phone} (${p.type})`).join(', ')]]}/><Block title="Дополнительно" rows={[['Дата рождения',c.birth_date],['Места торговли',c.trade_places?.join(', ')]]}/><Block title="История" rows={[['Первый импорт',c.first_import_at?.slice(0,10)],['Последнее обновление',c.updated_at?.slice(0,10)],['Последний импорт',c.last_import_at?.slice(0,10)],['Файл',c.last_import_file]]}/></div>}
function Block({title,rows}:any){return <section><h3>{title}</h3>{rows.map((r:any)=><p key={r[0]}><b>{r[0]}:</b> {r[1]||'—'}</p>)}</section>}
function ImportHistory({imports}:any){return <div className="card"><h2>История импортов</h2>{imports.map((i:any)=><p key={i.id}><b>{i.file_name}</b><br/>{i.imported_at?.slice(0,16)} · строк {i.rows_count} · +{i.added_count} · ↻{i.updated_count} · ошибок {i.error_count}</p>)}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
